In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [102]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [103]:
df_train = pd.read_csv(r'../data/raw/train.csv')
df_test = pd.read_csv(r'../data/raw/test.csv')
df_store = pd.read_csv(r'../data/raw/store.csv')

C:\Users\HP\AppData\Local\Temp\ipykernel_20392\3035748705.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv(r'../data/raw/train.csv')

In [104]:
print(df_train.shape)
print(df_test.shape)
print(df_store.shape)

(1001599, 10)
(1115, 9)
(1115, 10)

In [122]:
df_train["StateHoliday"] = df_train["StateHoliday"].astype(str)

In [105]:
df_train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Id
0,1,5,2015-07-17,4852,519,1,1,0,0,303445
1,2,5,2015-07-17,4518,495,1,1,0,1,959585
2,3,5,2015-07-17,6679,673,1,1,0,1,739744
3,4,5,2015-07-17,10514,1343,1,1,0,1,864001
4,5,5,2015-07-17,4355,513,1,1,0,1,981931

In [106]:
df_store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [107]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001599 entries, 0 to 1001598
Data columns (total 10 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1001599 non-null  int64
 1   DayOfWeek      1001599 non-null  int64
 2   Date           1001599 non-null  object
 3   Sales          1001599 non-null  int64
 4   Customers      1001599 non-null  int64
 5   Open           1001599 non-null  int64
 6   Promo          1001599 non-null  int64
 7   StateHoliday   1001599 non-null  object
 8   SchoolHoliday  1001599 non-null  int64
 9   Id             1001599 non-null  int64
dtypes: int64(8), object(2)
memory usage: 76.4+ MB

In [108]:
df_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [109]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1115 non-null   int64
 1   Store          1115 non-null   int64
 2   DayOfWeek      1115 non-null   int64
 3   Date           1115 non-null   object
 4   Customers      1115 non-null   int64
 5   Open           1115 non-null   int64
 6   Promo          1115 non-null   int64
 7   StateHoliday   1115 non-null   int64
 8   SchoolHoliday  1115 non-null   int64
dtypes: int64(8), object(1)
memory usage: 78.5+ KB

In [110]:
df_train["Date"] = pd.to_datetime(df_train["Date"])
df_test["Date"] = pd.to_datetime(df_test["Date"])

In [111]:
df_train.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
Id               0
dtype: int64

In [112]:
df_store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [113]:
df_train.describe()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,SchoolHoliday,Id
count,1.001599e+06,1.001599e+06,1001599,1.001599e+06,1.001599e+06,1.001599e+06,1.001599e+06,1.001599e+06,1.001599e+06
mean,5.584364e+02,3.998315e+00,2014-04-03 17:55:22.042054400,5.770573e+03,6.333030e+02,8.296454e-01,3.818944e-01,1.734596e-01,5.085189e+05
min,1.000000e+00,1.000000e+00,2013-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,2013-08-13 00:00:00,3.722000e+03,4.040000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.544410e+05
50%,5.580000e+02,4.000000e+00,2014-03-26 00:00:00,5.741000e+03,6.100000e+02,1.000000e+00,0.000000e+00,0.000000e+00,5.088100e+05
75%,8.380000e+02,6.000000e+00,2014-11-30 00:00:00,7.854000e+03,8.380000e+02,1.000000e+00,1.000000e+00,0.000000e+00,7.626425e+05
max,1.115000e+03,7.000000e+00,2015-07-17 00:00:00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.017207e+06
std,3.219092e+02,1.997350e+00,NaN,3.852568e+03,4.649430e+02,3.759442e-01,4.858511e-01,3.786443e-01,2.934647e+05

In [114]:
df_store.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [115]:
df = pd.merge(df_train, df_store, how='left', on='Store')
df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Id,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-17,4852,519,1,1,0,0,303445,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-17,4518,495,1,1,0,1,959585,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-17,6679,673,1,1,0,1,739744,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-17,10514,1343,1,1,0,1,864001,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-17,4355,513,1,1,0,1,981931,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [116]:
df.shape

(1001599, 19)

In [117]:
df.columns.tolist()

['Store',
 'DayOfWeek',
 'Date',
 'Sales',
 'Customers',
 'Open',
 'Promo',
 'StateHoliday',
 'SchoolHoliday',
 'Id',
 'StoreType',
 'Assortment',
 'CompetitionDistance',
 'CompetitionOpenSinceMonth',
 'CompetitionOpenSinceYear',
 'Promo2',
 'Promo2SinceWeek',
 'Promo2SinceYear',
 'PromoInterval']

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001599 entries, 0 to 1001598
Data columns (total 19 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1001599 non-null  int64
 1   DayOfWeek                  1001599 non-null  int64
 2   Date                       1001599 non-null  datetime64[ns]
 3   Sales                      1001599 non-null  int64
 4   Customers                  1001599 non-null  int64
 5   Open                       1001599 non-null  int64
 6   Promo                      1001599 non-null  int64
 7   StateHoliday               1001599 non-null  object
 8   SchoolHoliday              1001599 non-null  int64
 9   Id                         1001599 non-null  int64
 10  StoreType                  1001599 non-null  object
 11  Assortment                 1001599 non-null  object
 12  CompetitionDistance        998999 non-null   float64
 13  CompetitionOpenSinceMonth  683207 non-null   float64
 14  CompetitionOpenSinceYear   683207 non-null   float64
 15  Promo2                     1001599 non-null  int64
 16  Promo2SinceWeek            501184 non-null   float64
 17  Promo2SinceYear            501184 non-null   float64
 18  PromoInterval              501184 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(9), object(4)
memory usage: 145.2+ MB

In [119]:
df.duplicated().sum()

np.int64(0)

In [120]:
df.isnull().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
Id                                0
StoreType                         0
Assortment                        0
CompetitionDistance            2600
CompetitionOpenSinceMonth    318392
CompetitionOpenSinceYear     318392
Promo2                            0
Promo2SinceWeek              500415
Promo2SinceYear              500415
PromoInterval                500415
dtype: int64

In [121]:
df.isna().sum().sum()

np.int64(2140629)

## Observations

- **Target Variable:** Sales
- **Time Column:** Date
- **Merged Dataset Shape:** `df.shape` after merging train and store data
- **Missing Values:** mostly appear in competition- and promotion-related features such as CompetitionDistance, Promo2SinceYear, and PromoInterval
- **Categorical Features:** StoreType, Assortment, StateHoliday, and PromoInterval
- **Numerical Features:** Sales, CompetitionDistance, Promo2SinceYear, and other numeric store-level variables
- **Potential Data Leakage / Data Quality Issue:** review identifier and join-related columns before modeling, especially if they are not available at prediction time